import Head from "next/head";
import Sidebar from "@/components/Sidebar/Sidebar";
import Window from "@/components/Window/Window";
import Header from "@/components/Header/Header";
import {useSession} from "next-auth/react";
import { useMediaQuery } from '@mui/material';

const MainLayout = ({session, title, children, iconSrc, iconAlt}) => {
	// const { data: session, status, update } = useSession()
	// console.log(session)
	const matches = useMediaQuery('(max-width: 991px)');
	
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<div className="wrapper">
				{matches ? (null):(<Sidebar />)}
				<Header session={session} />
				<Window title={title} iconSrc={iconSrc} iconAlt={iconAlt}>
					{children}
				</Window>
			</div>
		</>
	);
};

export default MainLayout;